language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: djDFm/CKq0A9GNlGXsuCHMYGQr61lo1sUNE+0BRWRPALcvOOv8jxfOxTErxU5vw29FbFVsLqpaxDQcVZdaOhgWiEY3CGFaS2Y2JLi0aXm2nOQ8ByHfWS9cF4UYAfFXU4ffMr2nYIo9wHm9yQvbwvvZKGu1baugFV4po7N9HXzg814LLdIo8AYiVYi0FfnU0vEZf1HHzCFShL9zpOtNVx/zsQ9FdCcvGsdtwuHvbtQped+9264ri3Zu+6qeVSYCMrgJNXA8LzmZ2iQewtndN0j5brzem3ViREtRUzZYgSGZaIujiCm5N4qAict2R5AL9/2B+g3eH2Tsq7R5dQGXcDBTQujX1e7RJKVZl4r+UAF3bzU+Mttiv7oaT2FUHqjqw0igNbSZLCizl6aQ4A21JQpnT4u403jR3HnWOd57WiXbvJRwARTdFMOg6YuztPZth0kfjNSmIvYTdfaGQaXkCbtPf/NfgECArRgktUeLZedRa5TZ9XIX0FOtHXg6Or//oNKd6ciNXDAbQYE9jCy5H1ZyUOTIQ07p7egOSJ8TC3bryoeXe1dlfZ96xo1Bmb0rMhxZagroJru0RDxfOBdiuSMBSzFjeJfrp5JX1XxfDYQr3mlV/zlu0zD1l8kMBqe+EQuEZWKjyknZPx/1yhSncJ1RukuNSSD3X1TCg+KLkAQPE=
  app: vast-island-74754
  on:
    repo: J-Vega/shopping-list-integration-testing
